FROM node:22-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app

# --- Dependencies Stage ---
FROM base AS dependencies
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json .npmrc* ./

COPY apps/api/package.json ./apps/api/
COPY apps/web/package.json ./apps/web/
COPY apps/worker/package.json ./apps/worker/
COPY packages/ ./packages/
COPY layouts/ ./layouts/
RUN echo "public-hoist-pattern=*" >> .npmrc
RUN pnpm install

# --- Build Stage ---
FROM dependencies AS builder
COPY . .
RUN pnpm --filter web... build

# --- Runner Stage ---
FROM base AS runner
ENV NODE_ENV=production
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs


COPY --from=builder --chown=nextjs:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=nextjs:nodejs /app/packages ./packages
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next ./apps/web/.next
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/public ./apps/web/public
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/package.json ./apps/web/package.json

COPY --from=builder --chown=nextjs:nodejs /app/package.json ./package.json
COPY --from=builder --chown=nextjs:nodejs /app/pnpm-workspace.yaml ./pnpm-workspace.yaml

RUN chown nextjs:nodejs /app

USER nextjs
EXPOSE 3000
CMD ["pnpm", "--filter", "web", "start"]